name: '2.0$(Rev:.r)-prerelease'
trigger:
- master

variables:
  buildAgentVmImage: 'windows-latest'

pool:
  vmImage: $(buildAgentVmImage)

resources: 
  repositories:
  - repository: devops
    type: git
    name: cod/Cod.Infrastructures
    ref: main

stages:
- stage: Production
  jobs:
  - template: pipelines/jobs/GenericDotnetBuild.yml@devops
    parameters:
      nugetVSTSFeedID: 'cod/cod'
      projectToPublish: '**/Cod.Abstractions.csproj'