//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cod {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cod.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ERROR_0 {
            get {
                return ResourceManager.GetString("ERROR_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string ERROR_400 {
            get {
                return ResourceManager.GetString("ERROR_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Required.
        /// </summary>
        internal static string ERROR_401 {
            get {
                return ResourceManager.GetString("ERROR_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Required.
        /// </summary>
        internal static string ERROR_402 {
            get {
                return ResourceManager.GetString("ERROR_402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        internal static string ERROR_403 {
            get {
                return ResourceManager.GetString("ERROR_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string ERROR_404 {
            get {
                return ResourceManager.GetString("ERROR_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed.
        /// </summary>
        internal static string ERROR_405 {
            get {
                return ResourceManager.GetString("ERROR_405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Acceptable.
        /// </summary>
        internal static string ERROR_406 {
            get {
                return ResourceManager.GetString("ERROR_406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Timeout.
        /// </summary>
        internal static string ERROR_408 {
            get {
                return ResourceManager.GetString("ERROR_408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict.
        /// </summary>
        internal static string ERROR_409 {
            get {
                return ResourceManager.GetString("ERROR_409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition Failed.
        /// </summary>
        internal static string ERROR_412 {
            get {
                return ResourceManager.GetString("ERROR_412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string ERROR_423 {
            get {
                return ResourceManager.GetString("ERROR_423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Required.
        /// </summary>
        internal static string ERROR_426 {
            get {
                return ResourceManager.GetString("ERROR_426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Many Requests.
        /// </summary>
        internal static string ERROR_429 {
            get {
                return ResourceManager.GetString("ERROR_429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Error.
        /// </summary>
        internal static string ERROR_500 {
            get {
                return ResourceManager.GetString("ERROR_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upstream Error.
        /// </summary>
        internal static string ERROR_502 {
            get {
                return ResourceManager.GetString("ERROR_502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable.
        /// </summary>
        internal static string ERROR_503 {
            get {
                return ResourceManager.GetString("ERROR_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway Timeout.
        /// </summary>
        internal static string ERROR_504 {
            get {
                return ResourceManager.GetString("ERROR_504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Failure.
        /// </summary>
        internal static string ERROR_900 {
            get {
                return ResourceManager.GetString("ERROR_900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string ERROR_999 {
            get {
                return ResourceManager.GetString("ERROR_999", resourceCulture);
            }
        }
    }
}
